package com.tree.www.jsoup;

/**
 * @author crystal
 * @since 2021/11/17
 */
public class YellowPageConfig {
    public static final String[] SEARCH_TERMS = {
            "AC Repair",
            "Animal Shelters",
            "Appliance Repair",
            "Auto Body Shops",
            "Auto Glass Repair",
            "Auto Parts",
            "Auto Repair",
            "Bail Bonds",
            "Bankruptcy Attorneys",
            "Banks",
            "Barber Shops",
            "Beauty Salons",
            "Beauty Supplies",
            "Boat Insurance",
            "Breakfast Restaurants",
            "Business Insurance",
            "Car Accident Lawyers",
            "Car Detailing",
            "Car Insurance",
            "Carpet Cleaning",
            "Chinese Restaurants",
            "Cuban Restaurants",
            "Day Spas",
            "Dental Insurance",
            "Dentists",
            "Dermatologists",
            "Disability Insurance",
            "Divorce Attorneys",
            "Dog Training",
            "Doggy Day Cares",
            "Electricians",
            "Emergency Vets",
            "Endocrinologists",
            "Facial Salons",
            "Family Law Attorneys",
            "Flood Insurance",
            "Garage Door Repair",
            "Gynecologists",
            "Hair Removal",
            "Hair Stylists",
            "Hair Supplies",
            "Home Insurance",
            "Hospitals",
            "Insurance",
            "Italian Restaurants",
            "Kennels",
            "Korean Restaurants",
            "Liability Insurance",
            "Lie Detector Tests",
            "Life Insurance",
            "Massage",
            "Mexican Restaurants",
            "Mobile Pet Grooming",
            "Moving Companies",
            "Nail Salons",
            "Neurologists",
            "Oil Change",
            "Ophthalmologists",
            "Optometrists",
            "Pest Control Services",
            "Pet Boarding",
            "Pet Cemeteries",
            "Pet Grooming",
            "Physical Therapy",
            "Plumbers",
            "Podiatrists",
            "Police Departments",
            "Private Investigators",
            "Process Servers",
            "Roadside Assistance",
            "Seafood Restaurants",
            "Self Storage",
            "Stenographers",
            "Storage Units",
            "Sushi Bars",
            "Tax Attorneys",
            "Thai Restaurants",
            "Tire Shops",
            "Towing",
            "Vegetarian Restaurants",
            "Veterinary Clinics",
            "Window Tinting"
    };








    public static final String[] GEO_LOCATION_TERMS = {
            "Bristol",
            "Bronx",
            "Brooklyn",
            "Brownsville",
            "Brunswick",
            "Buckeye",
            "Buffalo",
            "Burbank",
            "Cairo",
            "California",
            "Cambridge",
            "Camden",
            "Canton",
            "Carson City",
            "Cedar Rapids",
            "Champaign-Urbana",
            "Chandler",
            "Charlotte",
            "Charlottesville",
            "Chattanooga",
            "Cherry Hill",
            "Chicago",
            "Chicago Suburbs",
            "Chico",
            "Chicoutimi",
            "Cincinnati",
            "Clearwater",
            "Cleveland",
            "Colby",
            "Colorado",
            "Colorado Springs",
            "Columbia",
            "Columbus",
            "Concord",
            "Connecticut",
            "Cookeville",
            "Cooksville",
            "Coolidge",
            "Corpus Christi",
            "Corvallis",
            "Council Bluffs",
            "Creston",
            "Cumberland",
            "Dallas",
            "Danville",
            "Davenport",
            "Dayton",
            "Deer Park",
            "DelRio",
            "Delaware",
            "Denton",
            "Denver",
            "Des Moines",
            "Detroit",
            "District of Columbia",
            "Dodge City",
            "Downey",
            "Dryden",
            "Dubuque",
            "Duluth",
            "Durham",
            "EastSt.Louis",
            "Eau Claire",
            "Edmonds",
            "ElDorado",
            "ElPaso",
            "Elizabeth",
            "Elmira",
            "Ely",
            "Endicott",
            "Enid",
            "Erie",
            "Eugene",
            "Eureka",
            "Evanston",
            "Evansville",
            "Everett",
            "Fairfax",
            "Fayetteville",
            "Findlay",
            "Fitchburg",
            "Flint",
            "Florence",
            "Florida",
            "Flushing",
            "Fort Collins",
            "Fort Dodge",
            "Fort Lauderdale",
            "Fort Myers",
            "Fort Wayne",
            "Fort William",
            "Fort Worth",
            "FortSmith",
            "Frankfort",
            "Frederick",
            "Fresno",
            "Gadsden",
            "Gainesville",
            "Galveston",
            "Garland",
            "Gary",
            "Georgia",
            "Gettysburg",
            "Glendale",
            "Gloversville",
            "Goodland",
            "Grand Island",
            "Grand Junction",
            "Grand Rapids",
            "GrandPrairie",
            "Green Bay",
            "Greensboro",
            "Greenville",
            "Guelph",
            "Gulfport",
            "Hackensack",
            "Hagerstown",
            "Hamilton",
            "Hammond",
            "Hannibal",
            "Harrisburg",
            "Hartford",
            "Hastings",
            "Hatteras",
            "Hattiesburg",
            "Hawaii",
            "Hempstead",
            "Herndon",
            "Hickory",
            "Hillsboro",
            "Hilton Head Island",
            "Hoboken",
            "Holly Springs",
            "Hopkinsville",
            "Houma",
            "Houston",
            "Huntsville",
            "Hutchinson",
            "Hyannis",
            "Idaho",
            "Illinois",
            "Independence",
            "Indiana",
            "Indianapolis",
            "Iowa",
            "Irvine",
            "Irving",
            "Ithaca",
            "Jackson",
            "Jacksonville",
            "Jefferson City",
            "Jellico",
            "Jersey City",
            "Johnstown",
            "Joliet",
            "Jonesboro",
            "Joplin",
            "Kalamazoo",
            "Kansas",
            "Kansas City",
            "Kelowna",
            "Kenora",
            "Kenosha",
            "Kensee",
            "Kent",
            "Kentucky",
            "KeyWest",
            "Kingston",
            "Kissimmee",
            "Kitchener",
            "Knoxville",
            "Kokomo",
            "La Crosse",
            "LaSalle",
            "Labrador City",
            "Lafayette",
            "Laguna",
            "Lake Charles",
            "Lancaster",
            "Lansing",
            "Las Vegas",
            "Latrobe",
            "Lawrence",
            "Lawton",
            "Lexington",
            "Lima",
            "Lincoln",
            "Little Rock",
            "Lloydminster",
            "London",
            "Long Beach",
            "Long Branch",
            "LongIsland",
            "Los Altos",
            "Los Angeles",
            "Lot",
            "Louisiana",
            "Louisville",
            "Lubbock",
            "Ludington",
            "Lufkin",
            "Macon",
            "Madison",
            "Maine",
            "Manchester",
            "Manhattan",
            "Mankato",
            "Manorville",
            "MapleGrove",
            "Marietta",
            "Marquette",
            "Maryland",
            "Mason City",
            "Massachusetts",
            "Mc Allen",
            "McAlester",
            "Memphis",
            "Mentor",
            "Meriden",
            "Methuen",
            "Miami",
            "Michigan",
            "Middletown",
            "Mile House",
            "Minneapolis",
            "Minnesota",
            "Mississauga",
            "Mississippi",
            "Missouri",
            "Moab",
            "Mobile",
            "Modesto",
            "Monroe",
            "Montana",
            "Monterey",
            "Montgomery",
            "Montreal",
            "Moorhead",
            "Morehead",
            "Mount Pleasant",
            "Muskegon",
            "Muskogee",
            "Myrtle Beach",
            "Naperville",
            "Naples",
            "Nashville",
            "Nebraska",
            "Nevada",
            "New Bedford",
            "New Brunswick",
            "New Castle",
            "New Hampshire",
            "New Haven",
            "New Jersey",
            "New Mexico",
            "New Orleans",
            "New York",
            "NewRoads",
            "Newark",
            "Newport News",
            "Niagara Falls",
            "Niguel",
            "Norfolk",
            "North Bay",
            "North Carolina",
            "North Dakota",
            "North Hollywood",
            "North Miami",
            "North Platte",
            "Northern Detroitsuburbs",
            "Norwalk",
            "Norwood",
            "O'Neill",
            "Oakland",
            "Oberlin",
            "Ogden",
            "Ohio",
            "Oklahoma",
            "Oklahoma City",
            "Olympia",
            "Omaha",
            "Oneida",
            "Oregon",
            "Orlando",
            "Oswego",
            "Ottawa",
            "Owensboro",
            "PaineBluff",
            "Palm Springs",
            "Palo Alto",
            "Panama City",
            "Pangnirtung",
            "Paris",
            "Pasadena",
            "Pascagoula",
            "Paterson",
            "Peabody",
            "Peekskill",
            "Pendleton",
            "Pennsylvania",
            "Pensacola",
            "Peoria",
            "Philadelphia",
            "Philadelphiasuburbs",
            "Phillipsburg",
            "Phoenix",
            "Pittsburgh",
            "Pittsfield",
            "Plano",
            "Platteville",
            "Pleasanton",
            "Portland",
            "Poughkeepsie",
            "Prince George",
            "Provo",
            "Pueblo",
            "Quebec",
            "Queens",
            "Racine",
            "Raleigh",
            "Reading",
            "Red Wing",
            "Regina",
            "Reno",
            "Rhode Island",
            "Richfield",
            "Richmond",
            "Rimouski",
            "Riverside",
            "Roanoke",
            "Rochester",
            "RockHill",
            "RockIsland",
            "Rockford",
            "Rockville",
            "Rome",
            "Sa nFernando",
            "Sacramento",
            "Saint George",
            "SaintPaul",
            "Salem",
            "Salina",
            "Salinas",
            "Salisbury",
            "Salt Lake City",
            "San Antonio",
            "San Bernardino",
            "San Diego",
            "San Francisco",
            "Santa Barbara",
            "SantaRosa",
            "Sarasota",
            "Saskatoon",
            "Sault Ste Marie",
            "SaultSte.Marie",
            "Savannah",
            "Saxton",
            "Schenectady",
            "Scottsbluff",
            "Scottsdale",
            "Scranton",
            "Seattle",
            "Sebastian",
            "Sherman",
            "Shreveport",
            "Sioux City",
            "Solana Beach",
            "Sonoma",
            "South Bend",
            "South Carolina",
            "South Dakota",
            "South Pasadena",
            "South SanFrancisco",
            "Spartanburg",
            "Spokane",
            "Springfield",
            "St Charles",
            "St Joseph",
            "St Louis",
            "St.John's",
            "St.Petersburg",
            "StCloud",
            "Staten Island",
            "Staunton",
            "Sudbury",
            "Superior",
            "Syracuse",
            "Tennessee",
            "Terre Haute",
            "Texarkana",
            "Texas",
            "Thomasville",
            "Thunder Bay",
            "Toledo",
            "Topeka",
            "Toronto",
            "Traverse City",
            "Trenton",
            "Troy",
            "Tulsa",
            "Tupelo",
            "Tyler",
            "Winston-Salem",
            "Wisconsin",
            "Worcester",
            "Wyoming",
            "Yonkers",
            "Youngstown"
    };
}
